### PR TITLE
AQGridViewCell’s background and content views configurable via Interface Builder; exception is logged and re-thrown

### PR DESCRIPTION
**Pull request by evadne**
As title — these commits allow the cell’s background and content views to be configurable via Interface Builder.  Also un-fixes a circumstance, where an exception is silently eaten.

The exception is, empirically, thrown when a cell returns nil for its reuse identifier.

### CODE REVIEW

**Comment by evadne** [comment]
I wonder why the three earlier commits are still there as they seem to have been merged already.  The interesting commits start from ca4def9.

**Comment by littlebigapps** [comment]
Hi there,

Thanks for this update. 

However, I'm still unable to get a AQGridViewCell designed in Interface builder to work - it just shows up as a blank white cell.

Would you be able to run through the steps required to create a custom AQGridViewCell with Interface builder after making these updates to AQGridViewCell.h/AQGridViewCell.m

Thank you!

**Comment by evadne** [comment]
As in a sample project? ;)

On Mar 18, 2011, at 8:13 AM, tappi
reply@reply.github.com
wrote:

**Comment by littlebigapps** [comment]
Well that would be ideal.. :) Sorry I am a bit of a newbie when it comes to hooking up stuff like this in interface builder...
Thanks again.

**Comment by adamgit** [comment]
@tappi  - the problem is that the original AQGridViewCell has been written wrongly for doing IB cells - instead of overriding UITableViewCell, it re-implements Apple's class, using the same internal variables.

Someone needs to delete the whole class, re-write it to extend UITVC, and then check for any bugs in the rest of the project that this exposes.

On a brief look, you need to at least refactor a few enum names and method names that shouldn't have been used (because they're identical to Apple-defined ones).

So ... it's a _lot_ of work to fix this (he says, having just spent half an hour trying to fix it. In particular, it's annoying that this project is using some identically named variables that Apple has as "true" private variables that aren't supported in iOS itself yet - so you can't even access them (they're not even in the docs - they only exist in the header files)

**Comment by evadne** [comment]
Closing my own pull request here.  It’s already irrelevant and can be achieved thru subclassing and introducing specific conveniences.

**Pull request closed without merging**
