### PR TITLE
Arc migration

### PR DESCRIPTION
**Pull request by aufflick**
Works great in my app and all my UI Automation tests pass, but then I don't use all features. I think it should be correct throughout though.

### CODE REVIEW

**Comment by evadne** [comment]
I think this can be merged once iOS 5 hits GM.  Ideas?

**Comment by Inza** [comment]
Let's merge it! Maybe (for back compatibility) a iOS5 branch could be created?

**Comment by kielgillard** [comment]
Personally very I'm keen for ARC migration. Haven't tested the patch though.

**Comment by Inza** [comment]
I have tested it successfully (this aufflick's pull request) in my iOS5 ARC-enabled app, but like aufflick, I do not use all features. That's the reason why I am talking about an iOS5 branch. Maybe we could create the branch and test it and merge it to the master after more developers will test it. What do you think, Alan?

**Comment by AlanQuatermain** [comment]
I've created an ARC-Beta branch and this will hopefully merge into there...

**Comment by AlanQuatermain** [comment]
Well darn, github merged it into master anyway. Sigh.

**Pull request merged**
