### PR TITLE
The tap event is added.

### PR DESCRIPTION
**Pull request by cheebow**
Added tap event

### CODE REVIEW

**Comment by evadne** [comment]
We already emit selection callbacks: is there a specific use case where observing it is not sufficient?

**Comment by cheebow** [comment]
Regardless of the situation of cell selection, I wanted tap event itself.

**Comment by evadne** [comment]
I think it’s best to use an UITapGestureRecognizer then going thru a cell-at-point indirection, it avoids adding a method in the delegate protocol.

**Comment by cheebow** [comment]
Thank you, helpful!

**Pull request closed without merging**
