### PR TITLE
Baca

### PR DESCRIPTION
**Pull request by SiriusDely**
I found a formula to calculate the cell size.
dw += (w % dw) / (w / dw);

The previous formula not quite good because it jumps the number of rows from 3 to 7.

Please take a look, thank you.

### CODE REVIEW

**Comment by evadne** [comment]
I think this looks good at first sight, could you elaborate cases in which you required the cell identifier to be read/write?  Thanks :)

**Comment by SiriusDely** [comment]
i forgot to explain that i am back to commit 1ab2696d660525faeaabd2515fcd1c34321f5c68 for this branch.
i am using this commit because i still need to compile my project on non-ARC.
so i already see that the formula for the cell size is already implemented differently for current master branch.

as for the cell identifier, i am using it on my cellForRowAtIndex like this:

```
CoverCell *cell = (CoverCell *)[inGridView dequeueReusableCellWithIdentifier:@"cell"];
if (!cell) {
    cell = [CoverCell cell];
    cell.reuseIdentifier = @"cell";
}
```

and getting compile error on cell.reuseIdentifier = @"cell" line.

again, maybe these all things already fixed on another commits. so forgive me to bother you for this. And please just close the pull request if you think it so. Thank you. :)

**Comment by evadne** [comment]
Hmmm.  Still interested in the dynamic cell width thing, seems like
something exposed via delegation already, would like to know the use
case.

Again, it is nice to get pull requests and your time is appreciated.  :)

• The ideal way to work with ARC and RRL code is to use the static
library target, this way things are clean.

• You can also go to the Compile Sources phase and and add some
compiler flags (-fobjc-arc ?), but this is not recommended, because
then you actively take in the burden of keeping up with the project
once the classes it uses have changed.  If you use a framework or a
static library, you can avoid the housework.

• Cell identifiers should be immutable to emphasize the fact that
whenever you grab a cell that was considered to hold the identifier X
it really is holding X.  In the case you attached a good approach is
to provide the identifier as a parameter to your initializer or
convenience.  Instead of +cell write +cellWithIdentifier:.

On Mar 11, 2012, at 3:24, Sirius Dely
reply@reply.github.com
wrote:

**Comment by SiriusDely** [comment]
for the cell identifiers to provide it on initialization. i got it now.

for the ARC things i still need to convey it more, i'll learn on your
suggestion.

thank you for the great explanation. :)

On Sun, Mar 11, 2012 at 2:43 AM, Evadne Wu <
reply@reply.github.com

> wrote:
> 
> Hmmm.  Still interested in the dynamic cell width thing, seems like
> something exposed via delegation already, would like to know the use
> case.
> 
> Again, it is nice to get pull requests and your time is appreciated.  :)
> 
>  The ideal way to work with ARC and RRL code is to use the static
> library target, this way things are clean.
> 
>  You can also go to the Compile Sources phase and and add some
> compiler flags (-fobjc-arc ?), but this is not recommended, because
> then you actively take in the burden of keeping up with the project
> once the classes it uses have changed.  If you use a framework or a
> static library, you can avoid the housework.
> 
>  Cell identifiers should be immutable to emphasize the fact that
> whenever you grab a cell that was considered to hold the identifier X
> it really is holding X.  In the case you attached a good approach is
> to provide the identifier as a parameter to your initializer or
> convenience.  Instead of +cell write +cellWithIdentifier:.

**Comment by evadne** [comment]
I’ll be closing the request for now.  Feel free to re-open it, or to make a new pull request for the dynamic cell width algorithm you mentioned, if it is something we can look into adding or refactoring.

If I recall correctly:
- `-[AQGridViewDelegate gridView:adjustCellFrame:withinGridCellFrame]` allows the delegate to adjust cell frames, since the cells are sized against the `_desiredCellSize`.
- The desired cell size comes from a default, or a delegate response to `-[AQGridViewDataSource portraitGridCellSizeForGridView:]`.
- The grid cell frames are the ones that evenly distributes the width of the grid view in sections.
- The cells are centered in those cell frames by default.

**Pull request closed without merging**
