### PR TITLE
Fixed Horizontal scroll when more than one row present

### PR DESCRIPTION
**Pull request by gabrielrinaldi**
Solution based on @RadhikaS work

### CODE REVIEW

**Comment by pzmudzinski** [comment]
When will it be included? Extremely needed!

**Comment by gabrielrinaldi** [comment]
There are some collateral damage with this. This breaks a lot of things in the app. You can try using this branch, but I've seen some odd behaviors with this.

**Comment by pzmudzinski** [comment]
Shoot... so how can I get horizontal scrolling working? Is anyone working on that?

**Comment by gabrielrinaldi** [comment]
I don't think so... If you are only using in horizontal mode you can try this branch.

**Comment by evadne** [comment]
I am back-logged on bringing the fix up to standard.

One hack you might consider is to apply a rotation transform and a flip
transform to the container view, then do the same thing to the cells.
- *

On Oct 7, 2012, at 11:00, Gabriel Rinaldi notifications@github.com wrote:

I don't think so...

—
Reply to this email directly or view it on
GitHubhttps://github.com/AlanQuatermain/AQGridView/pull/168#issuecomment-9210459.

**Comment by pzmudzinski** [comment]
I've tried this fix and didn't see any issues, but I am using only horizontal scrolling. One problem might be that index is counted column-by-column not row-by-row which is really confusing in horizontal layout:
1 3...
2 4...

Anyway, I have to say that it's easier to implement own horizontal grid view...

**Pull request closed without merging**
