### PR TITLE
Support for multiple selections

### PR DESCRIPTION
**Pull request by WanderingStar**
Added a new flag enabling multiple selections and replaced _selectedIndex with an NSIndexSet

### CODE REVIEW

**Comment by evadne** [comment]
Currently looking at this pull request.  A few points that I’d like to bounce:
- It seems like tapping on a selected cell does not toggle it — cell always stays selected.
- It might be better to use `allowsMultipleSelection` as it is more closer to NSCollectionView terminology.

Aside from that, great patch, merged already and doing cleanup.  Thanks.  :)

**Comment by WanderingStar** [comment]
Hmm. That's odd about the toggling. I'm definitely using that feature in the code that I forked this for. Did you find the problem already, or should I have a look at it?

That naming change sounds good.

**Comment by evadne** [comment]
Changes are now on the develop branch.  :)

On Jul 23, 2012, at 21:57, Aneel Nazareth
reply@reply.github.com
wrote:

**Comment by diegomagal** [comment]
Hi,

I tried to use this code on the develop branch but it do not seem to be alreayd added. Could you check it please?

**Comment by evadne** [comment]
This feature is not supported yet.  You might want to look into alternate
solutions in the mean time.  Sorry for the inconvenience.  :)

On Aug 15, 2012, at 6:03, diegomagal notifications@github.com wrote:

Hi,

I tried to use this code on the develop branch but it do not seem to be
alreayd added. Could you check it please?

—
Reply to this email directly or view it on
GitHubhttps://github.com/AlanQuatermain/AQGridView/pull/126#issuecomment-7755185.

**Comment by fbayle** [comment]
Hi !

This AQGridView is a very nice framework, and I'm already toying with the dev version, as I need multiple selection.

It occurred to me that when setAllowsMultipleSelection is called with false, you should unselect the selected items or, at least, add a unselectAll method. 

For now, here is my quick and dirty way to address that :

```
- (void) setAllowsMultipleSelection:(BOOL)allowsMultipleSelection 
{
    _flags.allowsMultipleSelection = (allowsMultipleSelection ? 1 : 0);
    //  We should unselect the items...
    if (!allowsMultipleSelection)
    {
        if ([self.selectionIndexes count]>0)
        {
            [self beginUpdates];
            int currentIndex=[self.selectionIndexes firstIndex];
            while (currentIndex!=NSNotFound)
            {
                [self deselectItemAtIndex:currentIndex animated:YES];
                currentIndex=[self.selectionIndexes indexGreaterThanIndex:currentIndex];
            }
            [self endUpdates];
        }
    }
}
```

Frederic

**Comment by evadne** [comment]
@fbayle I think you should be able to deselect things by setting
selectionIndexes to nil.  Will check shortly.

On Aug 21, 2012, at 6:46, fbayle notifications@github.com wrote:

Hi !

This AQGridView is a very nice framework, and I'm already toying with the
dev version, as I need the multiple selection.

It occurred to me that when setAllowsMultipleSelection is called with
false, you should unselect the selected items or, at least, add a
unselectAll method.

For now, here is my quick and dirty way to address that :
- (void) setAllowsMultipleSelection:(BOOL)allowsMultipleSelection
  {
  _flags.allowsMultipleSelection = (allowsMultipleSelection ? 1 : 0);
  //  We should unselect the items...
  if (!allowsMultipleSelection)
  {
      if ([self.selectionIndexes count]>0)
      {
          [self beginUpdates];
          int currentIndex=[self.selectionIndexes firstIndex];
          while (currentIndex!=NSNotFound)
          {
              [self deselectItemAtIndex:currentIndex animated:YES];
              currentIndex=[self.selectionIndexes
  indexGreaterThanIndex:currentIndex];
          }
          [self endUpdates];
      }
  }
  }

Frederic

—
Reply to this email directly or view it on
GitHubhttps://github.com/AlanQuatermain/AQGridView/pull/126#issuecomment-7901252.

**Comment by synergie7** [comment]
I needed multiple selections, so I pulled the Dev branch.

However there appears to be a bug in that the _selectedIndices array is not cleared during  reloadData.

In my case I'm deleting items from the list based on multiple selections, but I've found that if the user deletes a single item, (I then reload the gridView), then goes back and deletes another single item, the _selectedIndices.count shows 2 on the second delete attempt because selectedIndices still contains the index from the previous selection (prior to the reload).

My hack / fix for this has been to add  [_selectedIndices removeAllIndexes]; to -(void) reloadData in AQGrivdView.m but I'm not sure if this is the best way to do it, or even if this functionality would suit everyone.
i.e I'm not sure if some people want the selection list to be retained even after a reload.

**Comment by chadpod** [comment]
I added support for multiple selection a while back, but am not using it anymore.  Figured I would post here in case it is of any value to you guys, as I'm thinking of deleting the fork.  2964b150f0c74ef94cdb585f58baf8489763c3ed

**Comment by synergie7** [comment]
Hi Chadpod,

I'm using it in my app "Personal Wiki" (iPad). As I allow users to do multiple selections on items in the grid, which they can then delete.

Rather than deleting the fork and hence removing this functionality, is there any way it can be rolled into the master branch ?

**Comment by evadne** [comment]
It seems that `allowsMultipleSelection` is already on master for a long while.

**Comment by chadpod** [comment]
@evadne I see it in development, but not master?  @synergie7 I'll leave my fork as is for the time being, but I recommend you move to the official branch, as I haven't maintained my implementation.  Glad you found it of use anyway!

**Comment by evadne** [comment]
Yes — it is on development indeed.

**Comment by synergie7** [comment]
OK.

I'll switch to the master branch.

Thanks

**Comment by synergie7** [comment]
Sorry. I mean I'll use the Dev branch.

To be honest, its been ages since I last worked on the app, I can't really remember which branch I ended up using. 
I think it was probably just the Dev branch.

I'm not sure if I used @chadpod's fork (probably not).

**Pull request closed without merging**
