### PR TITLE
Content view leaks

### PR DESCRIPTION
**Pull request by darrylhthomas**
Under certain conditions, content views were being leaked.  I believe this is the same as issue #55.  The bug was difficult to reproduce consistently, but I believe this is the fix.  Have tested each of the example apps to make sure this doesn't introduce crashes.

Thanks.

### CODE REVIEW

**Comment by andyzaharia** [comment]
Applied your fix in my code, and it doesn't fix issue #55, very weird one.

**Comment by darrylhthomas** [comment]
Darn.  Guess we had different issues. I'm in the middle preparing a release, but if I find some spare time, I'll take a look at the project you posted and see if I can reproduce it on my end.

D

**Comment by andyzaharia** [comment]
Yea, no problem, I'm trying to figure it out right now before going to bed, if I find something I will let you know.

Thanks.

**Comment by andyzaharia** [comment]
I fixed the issue #55 on my side, apparently the _contentView View from AQGridViewCell is not initialized after [super initWithFrame...], this is obvious why it isnt, but the problem is, somehow AQGridViewCell manages to screw it up when I try to add another view(in my case an UIImageView) to _contentView, AQGridViewCell should initialize the _contentView and then add my view to it, but this particular case seems to fail. I fixed the problem by calling [self contentView], from my custom class before adding my view(UIImageView). 
So I guess the problem is somewhere in the initialization code for the _contentView ivar. I wasnt able to dig too much into the AQGridViewCell's code, but if you have the idea how to fix, please go ahead.

``` Objective-C
- (id) initWithFrame: (CGRect) frame reuseIdentifier: (NSString *) aReuseIdentifier
{
    self = [super initWithFrame: frame reuseIdentifier: aReuseIdentifier];
    if (self)
    {       
       [self contentView]; // fix here

        _imageView = [[UIImageView alloc] initWithFrame: CGRectMake(0.0, 0.0, 60.0, 60.0)];
        [_imageView setBackgroundColor:[UIColor clearColor]];

        [self.contentView addSubview: _imageView];
        [self.contentView setBackgroundColor:[UIColor clearColor]];
        self.backgroundColor = [UIColor clearColor];

        self.selectionStyle = AQGridViewCellSelectionStyleGray;

        NSLog(@"TIconCell init");
    }
    return self;
}

```

Thanks, and have a good day ! :)

**Pull request merged**
